Primer entrega
iaw-2022/VictoriaMartinSahagun-laravel pull request #1
Opened 2022-04-21 19:19 UTC by VictoriaMartinSahagun

email ususario:
admin@admin.com
password:
admin

2022-05-03 23:04 UTC, dcm-uns requested changes
Falta el link de Heroku

2022-05-03 23:10 UTC, VictoriaMartinSahagun commented
Buenas tardes, perdon me olvide que tenia que ponerlo. Aqui lo adjunto:
http://proyecto-balcon.herokuapp.com/

2022-05-05 15:14 UTC, dcm-uns requested changes
La registración no funciona (500-server error)

2022-05-05 15:46 UTC, VictoriaMartinSahagun commented
Buenos dias, ya solucione el problema.

2022-05-05 21:02 UTC, dcm-uns approved these changes

2022-05-06 01:55 UTC, merged